### ISSUE TITLE
temporary bg_inactive color change

### ISSUE THREAD

**Issue by klooj** [ishan9299/modus-theme-vim#10]
Thank you for sharing these themes. They coalesce with nvim so comprehensively that I never think of themes as a separate concern from the editor or the task at hand anymore. 

The occasional exception is when I want to temporarily change a color that is unrelated to syntax highlighting for the current buffer; usually the inactive_bg color when I have multiple nvim instances open. Is there an ex/lua command that I can use? I am a little lost in the sauce in the handoff from modus to colorbuddy and cannot seem to pinpoint the correct color name/group/palette.

**Comment by ishan9299** [comment]
If you want to change the inactive window color then use the `hi :NormalNC guibg=#{your-color-code} guifg=#{your-color-code}`

**Comment by klooj** [comment]
thank you
