### ISSUE TITLE
temporarily change bg_inactive?

### ISSUE THREAD

**Issue by klooj** [ishan9299/modus-theme-vim#11]
Thank you for sharing these themes. They coalesce with nvim so comprehensively that I never think of themes as a separate concern from the editor or the task at hand anymore. 

The occasional exception is when I want to temporarily change a color that is unrelated to syntax highlighting for the current buffer; usually the inactive_bg color when I have multiple nvim instances open. Is there an ex/lua command that I can use? I am a little lost in the sauce in the handoff from modus to colorbuddy and cannot seem to pinpoint the correct color name/palette without defining entirely new groups. 

Thanks again.

**Comment by ishan9299** [comment]
The theme already highlights the background color differently for inactive splits. I suppose you are using tmux? If so it might be possible to do so but right now I can't work on it a pull request would be appreciated.

**Comment by klooj** [comment]
Na it's a me thing.   I'd say 87% of the time the builtin function for inactive splits works great but, even without tmux, I find myself inevitably working across multiple hosts and getting reckless with transparent floating terminal windows.  I never actually need to change the whole buffer's background, just occasionally I find myself wanting  to "flag"  or differentiate the current window from  _two_  other backgrounds until it is closed.  

I thought I was missing something obvious and that colorbuddy would let me shoot off a hex value on the fly for modus to inherit once, but I see now it's much more delicate than that.  

I'll try my hand at a pull request.

**Comment by klooj** [comment]
I am going to get to this but have not had the time to get back to it yet. closing this out until i start working on a pull request.
