### ISSUE TITLE
the highlight on current line looks broken

### ISSUE THREAD

**Issue by peterwu** [ishan9299/modus-theme-vim#13]
Not sure if this is by design or a bug but if you look at line 109 in the screenshot below, you'll notice that the currently highlighted line's foreground looks broken. At least, some words are not highlighted with the expected foreground colour.

![Screenshot from 2021-05-13 22-10-23](https://user-images.githubusercontent.com/584751/118210277-4bee2a80-b438-11eb-8730-5b4f6dbfac3e.png)

**Comment by ishan9299** [comment]
Yeah I will look into it. I had noticed this before but I forgot about it. 
Edit:-
Actually are you talking about the background color of cursorline? because from what I see the keywords are highlighted fine.

**Comment by ishan9299** [comment]
I have attempted a fix with the commit b6667db70913b1313be65ab81104f38abff37274 can you try it out ?

**Comment by peterwu** [comment]
Yup. just tried your fix and it works great! Thanks a lot!
