### ISSUE TITLE
some letters are invisible under operandi

### ISSUE THREAD

**Issue by peterwu** [ishan9299/modus-theme-vim#14]
So far, I notice the tags below will *hide* the letters that follow.
`
<leader>
<localleader>
<silent>
nnoremap
`

Look at line 24 and onward.

With the default color scheme, it should look like this:
![Screenshot from 2021-05-16 21-39-33](https://user-images.githubusercontent.com/584751/118421712-96b5af80-b68f-11eb-8d63-4f4b4a4d47a1.png)

With the operandi theme, letters following <leader> are invisible if not under cursor. When under cursor, it's quite difficult to identify.
![Screenshot from 2021-05-16 21-39-44](https://user-images.githubusercontent.com/584751/118421763-b51bab00-b68f-11eb-96a7-1c5dea013655.png)

Hope these screenshots help clarify the issue. I can provide more if needed. Thanks.

**Comment by ishan9299** [comment]
should be fixed now.

**Comment by peterwu** [comment]
Excellent! Thx.
