### ISSUE TITLE
Neovim 0.5 native LSP diagnostics

### ISSUE THREAD

**Issue by bnjmnt4n** [ishan9299/modus-theme-vim#17]
When the floating window for native LSP diagnostics is open, some text cannot be seen:

![image](https://user-images.githubusercontent.com/813865/124349644-c78f7b00-dc22-11eb-88ef-6d037597ef54.png)

After selection:
![image](https://user-images.githubusercontent.com/813865/124349646-d413d380-dc22-11eb-8139-6de79d80d24a.png)

**Comment by ishan9299** [comment]
1798720025781f7b709f92ef359d777d0e129404 I added some stuff. Can you update and check?

**Comment by bnjmnt4n** [comment]
Thanks a lot @ishan9299, it looks good now!
