### ISSUE TITLE
modus_dim_inactive_window = 0 is no longer respected

### ISSUE THREAD

**Issue by daveriedstra** [ishan9299/modus-theme-vim#29]
On `NVIM v0.10.0-dev` setting `modus_dim_inactive_window = 0` is ignored and inactive panes / windows are still dimmed.

**Comment by ishan9299** [comment]
are you setting the variable before or after applying the colorscheme ?

**Comment by daveriedstra** [comment]
aha, no I wasn't, and doing so fixed it. Thanks! Curiously, it had been working until recently...
