### ISSUE TITLE
No yellow comments nor green strings

### ISSUE THREAD

**Issue by TimoKramer** [ishan9299/modus-theme-vim#31]
Hi,
I just rewrote my nvim-config with [kickstart](https://github.com/nvim-lua/kickstart.nvim) and realized that I never had yellow comments nor green strings working. I always had it enabled but it never worked, not in lua and not in any other language I used.

This is my piece of config regarding modus:
```
return {
  "ishan9299/modus-theme-vim",
  lazy = false,
  priority = 1000,
    config = function()
      vim.cmd([[colorscheme modus-operandi]])
      vim.g.modus_yellow_comments = true
      vim.g.modus_green_strings = true
    end,
}
```
and this is a screenshot:
![image](https://github.com/ishan9299/modus-theme-vim/assets/4785848/dc28d8c8-2321-4543-9948-79daa96e348d)

I really love this theme. I am open to help if someone can tell me what the problem is and points me in the right direction.

Thanks

**Comment by savchenko** [comment]
The following approach works:

```lua
vim.cmd[[
let g:modus_yellow_comments = 1
let g:modus_green_strings = 1
]]
vim.cmd('colorscheme modus-vivendi')
```

However native Lua does not:

```lua
vim.g.modus_yellow_comments = true
vim.g.modus_green_strings = true
vim.cmd('colorscheme modus-vivendi')
```

**Comment by ishan9299** [comment]
set 1 instead of true in lua.

**Comment by ishan9299** [comment]
the code checks if value is 1 or 0
https://github.com/ishan9299/modus-theme-vim/blob/4d827fbf1aad55f4d62225f7b999efc5023864a3/lua/modus-themes/highlights.lua#L365

**Comment by ishan9299** [comment]
If the issue persists re-open.
