### ISSUE TITLE
Error when trying to set colorscheme in neovim v0.4.4

### ISSUE THREAD

**Issue by jakesco** [ishan9299/modus-theme-vim#4]
Hi there,

While attempting to set the theme with `colorscheme modus-vivendi` I get the following error: 
```
Error detected while processing 
/home/<redacted>/.local/share/nvim/site/plugged/modus-theme-vim/colors/modus-vivendi.vim: 
line 2: 
E5105: Error while calling lua chunk: 
.../nvim/site/plugged/modus-theme-vim/lua/modus-vivendi.lua:7: attempt to call field 'cmd' (a nil value)
```
I use vim-plug and installed colorbuddy as directed in the README.

**Comment by ishan9299** [comment]
It seems that the problem was that I was using the wrappers around vim.api functions and those are available in the nightly version. It will fixed soon thanks for opening the issue.

**Comment by ishan9299** [comment]
It should be fixed now. Please update the colorscheme.

**Comment by ishan9299** [comment]
Sorry I made a mistake in the commit d0df9f34bf07b076f0f4fcc43beaae4e9d93b22e it should be fixed now 571bff557208f7364f5bf717140b3c08fe204cc3.

**Comment by jakesco** [comment]
Thank you so much!

I updated and now get this error:

```
line    2:
E5105: Error while calling lua chunk: .../nvim/site/plugged/modus-theme-vim/lua/modus-vivendi.lua:13: attempt to index field 'fn' (a nil value)
```

I was able to get it working for now by commenting out

``` lua
if vim.fn.exists('syntax_on') then
  vim.api.nvim_command('syntax reset')
end
```

and 

``` lua
local flag = vim.fn.exists('g:modus_faint_syntax')
if flag == 0 then
  vim.api.nvim_set_var('modus_faint_syntax', 0)
end
local faint = vim.api.nvim_get_var('modus_faint_syntax')
```

**Comment by ishan9299** [comment]
It seems lua is a bit hit or miss for 0.4.4 I have moved some parts of code to vimscript so that you won't get errors. But now to apply the colorscheme you will have to use `lua require('colorbuddy').colorscheme('modus-operandi')`

**Comment by jakesco** [comment]
The update is working. 

Thanks for working on this!
