### ISSUE TITLE
getting started optimisations

### ISSUE THREAD

**Issue by matu3ba** [ishan9299/modus-theme-vim#8]
1. is missing how to enable termguicolors
2. `Plug 'ishan9299/modus-theme-vim', {'branch': 'stable'} -- only if you are not using nightly` I guess one can remove branch stable, if one is not on nightly. This could be more explicit in the formulation.
3. recommended init.lua setup tutorial would be great
4. use 1 setup option and move the other to package_setup.md (with linking to it)

**Comment by ishan9299** [comment]
> 1. is missing how to enable termguicolors

The colorscheme will work even if termguicolors is not set but it is enabled automatically maybe because of colorbuddy.

> 3. recommended init.lua setup tutorial would be great

The README does state how to set the colorscheme and it is in lua.

Also will update the README on how to setup the colorscheme.
