### ISSUE TITLE
visualise color palette

### ISSUE THREAD

**Issue by matu3ba** [ishan9299/modus-theme-vim#9]
Probably showing all bgs, fgs, reds, etc for modus vivendi and modus operandi for tainted and normal mode.

Intention is to have an fast and complete estimation of contrast etc on different displays/technologies.

**Comment by ishan9299** [comment]
Not sure what you mean but if you want the color codes then [modus-operandi](https://github.com/ishan9299/modus-theme-vim/blob/be73cb5ea4aa08d1c15933b207319b527b4cdb1f/lua/modus-operandi.lua#L4-L175) and [modus-vivendi](https://github.com/ishan9299/modus-theme-vim/blob/be73cb5ea4aa08d1c15933b207319b527b4cdb1f/lua/modus-vivendi.lua#L3-L173)

**Comment by matu3ba** [comment]
I was thinking at something like [this](https://github.com/sonph/onehalf/blob/master/screenshots/dark.png) or [this](https://github.com/sonph/onehalf/blob/master/screenshots/light.png). 

Ideally would be providing instructions to generate a vector graphics (without background), so that the user can customize it more easily.

**Comment by ishan9299** [comment]
Ok will do that.
